import{a as L,i as d,S as b}from"./assets/vendor-09d7c26e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();async function u(s,e){const a="https://pixabay.com/api/",n=new URLSearchParams({key:"43183854-3276a6d2cec346ebc07eac88c",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:e});return(await L.get(a,{params:n})).data}function m(s){return s.map(e=>`<div class="card">
        <a class="gallery-link" href="${e.largeImageURL}">
            <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
          </a>
          <ul class="list">
            <li class="item">Likes: <span>${e.likes}</span></li>
            <li class="item">Views: <span>${e.views}</span></li>
            <li class="item">Comments: <span>${e.comments}</span></li>
            <li class="item">Downloads: <span>${e.downloads}</span></li>
          </ul>
          </div>`).join("")}const o={formEl:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loadElem:document.querySelector(".loader"),btnLoadMore:document.querySelector(".js-btn-load")};let l,i=1,f=0;const w=14;o.formEl.addEventListener("submit",S);o.btnLoadMore.addEventListener("click",M);async function S(s){s.preventDefault(),y(),l=o.formEl.elements.searchImages.value.trim(),o.gallery.innerHTML="",i=1,l.length||d.error({color:"yellow",message:" Please fill in the field for search query.",position:"topRight"});try{const e=await u(l,i);f=Math.ceil(e.total/w),e.hits.length||d.error({color:"red",message:"❌ Sorry, there are no images matching your search query. Please try again!",position:"topRight"});const a=m(e.hits);o.gallery.insertAdjacentHTML("beforeend",a),h(),new b(".gallery a").refresh()}catch(e){console.log(e)}g(),p(),o.formEl.reset()}async function M(){y(),i+=1;const s=await u(l,i),e=m(s.hits);o.gallery.insertAdjacentHTML("beforeend",e),g(),p()}function p(){i>=f?v():h()}function h(){o.btnLoadMore.classList.remove("hidden")}function v(){o.btnLoadMore.classList.add("hidden")}function y(){o.loadElem.classList.remove("hidden")}function g(){o.loadElem.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
